spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: fallbackHandler
            fallbackUri: forward:/fallback
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
            key-resolver: "#{@apiKeyResolver}"
  redis:
    host: 127.0.0.1
    port: 6379
    password: password

hystrix:
  command:
    fallbackCmdA:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
